//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServicioCineWeb.PeliculaWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", ConfigurationName="PeliculaWebService.PeliculaWS")]
    public interface PeliculaWS {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/eliminarPelic" +
            "ulaRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/eliminarPelic" +
            "ulaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaResponse eliminarPelicula(AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/eliminarPelic" +
            "ulaRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/eliminarPelic" +
            "ulaResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaResponse> eliminarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/registrarPeli" +
            "culaRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/registrarPeli" +
            "culaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.PeliculaWebService.registrarPeliculaResponse registrarPelicula(AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/registrarPeli" +
            "culaRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/registrarPeli" +
            "culaResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.registrarPeliculaResponse> registrarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/actualizarPel" +
            "iculaRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/actualizarPel" +
            "iculaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaResponse actualizarPelicula(AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/actualizarPel" +
            "iculaRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/actualizarPel" +
            "iculaResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaResponse> actualizarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/listarPelicul" +
            "asRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/listarPelicul" +
            "asResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutoServicioCineWeb.PeliculaWebService.listarPeliculasResponse listarPeliculas(AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/listarPelicul" +
            "asRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/listarPelicul" +
            "asResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.listarPeliculasResponse> listarPeliculasAsync(AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/buscarPelicul" +
            "aPorIdRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/buscarPelicul" +
            "aPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdResponse buscarPeliculaPorId(AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/buscarPelicul" +
            "aPorIdRequest", ReplyAction="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/PeliculaWS/buscarPelicul" +
            "aPorIdResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdResponse> buscarPeliculaPorIdAsync(AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPelicula", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class eliminarPeliculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarPeliculaRequest() {
        }
        
        public eliminarPeliculaRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPeliculaResponse", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class eliminarPeliculaResponse {
        
        public eliminarPeliculaResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class pelicula : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clasificacionField;
        
        private int duracionMinField;
        
        private bool estaActivaField;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        private funcion[] funcionesField;
        
        private genero[] generosField;
        
        private string imagenUrlField;
        
        private int peliculaIdField;
        
        private bool peliculaIdFieldSpecified;
        
        private string sinopsisEnField;
        
        private string sinopsisEsField;
        
        private string tituloEnField;
        
        private string tituloEsField;
        
        private int usuarioModificacionField;
        
        private bool usuarioModificacionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clasificacion {
            get {
                return this.clasificacionField;
            }
            set {
                this.clasificacionField = value;
                this.RaisePropertyChanged("clasificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int duracionMin {
            get {
                return this.duracionMinField;
            }
            set {
                this.duracionMinField = value;
                this.RaisePropertyChanged("duracionMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estaActiva {
            get {
                return this.estaActivaField;
            }
            set {
                this.estaActivaField = value;
                this.RaisePropertyChanged("estaActiva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaModificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("funciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public funcion[] funciones {
            get {
                return this.funcionesField;
            }
            set {
                this.funcionesField = value;
                this.RaisePropertyChanged("funciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public genero[] generos {
            get {
                return this.generosField;
            }
            set {
                this.generosField = value;
                this.RaisePropertyChanged("generos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string imagenUrl {
            get {
                return this.imagenUrlField;
            }
            set {
                this.imagenUrlField = value;
                this.RaisePropertyChanged("imagenUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int peliculaId {
            get {
                return this.peliculaIdField;
            }
            set {
                this.peliculaIdField = value;
                this.RaisePropertyChanged("peliculaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool peliculaIdSpecified {
            get {
                return this.peliculaIdFieldSpecified;
            }
            set {
                this.peliculaIdFieldSpecified = value;
                this.RaisePropertyChanged("peliculaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sinopsisEn {
            get {
                return this.sinopsisEnField;
            }
            set {
                this.sinopsisEnField = value;
                this.RaisePropertyChanged("sinopsisEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sinopsisEs {
            get {
                return this.sinopsisEsField;
            }
            set {
                this.sinopsisEsField = value;
                this.RaisePropertyChanged("sinopsisEs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string tituloEn {
            get {
                return this.tituloEnField;
            }
            set {
                this.tituloEnField = value;
                this.RaisePropertyChanged("tituloEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tituloEs {
            get {
                return this.tituloEsField;
            }
            set {
                this.tituloEsField = value;
                this.RaisePropertyChanged("tituloEs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioModificacionSpecified {
            get {
                return this.usuarioModificacionFieldSpecified;
            }
            set {
                this.usuarioModificacionFieldSpecified = value;
                this.RaisePropertyChanged("usuarioModificacionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class funcion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private boleto[] boletosField;
        
        private bool estaActivaField;
        
        private localDateTime fechaHoraField;
        
        private localDateTime fechaModificacionField;
        
        private string formatoProyeccionField;
        
        private int funcionIdField;
        
        private bool funcionIdFieldSpecified;
        
        private string idiomaField;
        
        private pelicula peliculaField;
        
        private sala salaField;
        
        private bool subtitulosField;
        
        private bool subtitulosFieldSpecified;
        
        private int usuarioModificacionField;
        
        private bool usuarioModificacionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("boletos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public boleto[] boletos {
            get {
                return this.boletosField;
            }
            set {
                this.boletosField = value;
                this.RaisePropertyChanged("boletos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estaActiva {
            get {
                return this.estaActivaField;
            }
            set {
                this.estaActivaField = value;
                this.RaisePropertyChanged("estaActiva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string formatoProyeccion {
            get {
                return this.formatoProyeccionField;
            }
            set {
                this.formatoProyeccionField = value;
                this.RaisePropertyChanged("formatoProyeccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int funcionId {
            get {
                return this.funcionIdField;
            }
            set {
                this.funcionIdField = value;
                this.RaisePropertyChanged("funcionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool funcionIdSpecified {
            get {
                return this.funcionIdFieldSpecified;
            }
            set {
                this.funcionIdFieldSpecified = value;
                this.RaisePropertyChanged("funcionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public pelicula pelicula {
            get {
                return this.peliculaField;
            }
            set {
                this.peliculaField = value;
                this.RaisePropertyChanged("pelicula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public sala sala {
            get {
                return this.salaField;
            }
            set {
                this.salaField = value;
                this.RaisePropertyChanged("sala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool subtitulos {
            get {
                return this.subtitulosField;
            }
            set {
                this.subtitulosField = value;
                this.RaisePropertyChanged("subtitulos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtitulosSpecified {
            get {
                return this.subtitulosFieldSpecified;
            }
            set {
                this.subtitulosFieldSpecified = value;
                this.RaisePropertyChanged("subtitulosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioModificacionSpecified {
            get {
                return this.usuarioModificacionFieldSpecified;
            }
            set {
                this.usuarioModificacionFieldSpecified = value;
                this.RaisePropertyChanged("usuarioModificacionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class boleto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int boletoIdField;
        
        private bool boletoIdFieldSpecified;
        
        private estadoBoleto estadoField;
        
        private bool estadoFieldSpecified;
        
        private funcion funcionField;
        
        private venta ventaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int boletoId {
            get {
                return this.boletoIdField;
            }
            set {
                this.boletoIdField = value;
                this.RaisePropertyChanged("boletoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boletoIdSpecified {
            get {
                return this.boletoIdFieldSpecified;
            }
            set {
                this.boletoIdFieldSpecified = value;
                this.RaisePropertyChanged("boletoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoBoleto estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public funcion funcion {
            get {
                return this.funcionField;
            }
            set {
                this.funcionField = value;
                this.RaisePropertyChanged("funcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public venta venta {
            get {
                return this.ventaField;
            }
            set {
                this.ventaField = value;
                this.RaisePropertyChanged("venta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public enum estadoBoleto {
        
        /// <remarks/>
        VALIDO,
        
        /// <remarks/>
        USADO,
        
        /// <remarks/>
        ANULADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class venta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoVenta estadoField;
        
        private bool estadoFieldSpecified;
        
        private localDateTime fechaHoraField;
        
        private double impuestosField;
        
        private bool impuestosFieldSpecified;
        
        private metodoPago metodoPagoField;
        
        private bool metodoPagoFieldSpecified;
        
        private double subtotalField;
        
        private bool subtotalFieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        private usuario usuarioField;
        
        private int ventaIdField;
        
        private bool ventaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoVenta estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public localDateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double impuestos {
            get {
                return this.impuestosField;
            }
            set {
                this.impuestosField = value;
                this.RaisePropertyChanged("impuestos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool impuestosSpecified {
            get {
                return this.impuestosFieldSpecified;
            }
            set {
                this.impuestosFieldSpecified = value;
                this.RaisePropertyChanged("impuestosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public metodoPago metodoPago {
            get {
                return this.metodoPagoField;
            }
            set {
                this.metodoPagoField = value;
                this.RaisePropertyChanged("metodoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metodoPagoSpecified {
            get {
                return this.metodoPagoFieldSpecified;
            }
            set {
                this.metodoPagoFieldSpecified = value;
                this.RaisePropertyChanged("metodoPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subtotalSpecified {
            get {
                return this.subtotalFieldSpecified;
            }
            set {
                this.subtotalFieldSpecified = value;
                this.RaisePropertyChanged("subtotalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
                this.RaisePropertyChanged("totalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int ventaId {
            get {
                return this.ventaIdField;
            }
            set {
                this.ventaIdField = value;
                this.RaisePropertyChanged("ventaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ventaIdSpecified {
            get {
                return this.ventaIdFieldSpecified;
            }
            set {
                this.ventaIdFieldSpecified = value;
                this.RaisePropertyChanged("ventaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public enum estadoVenta {
        
        /// <remarks/>
        PENDIENTE,
        
        /// <remarks/>
        COMPLETADA,
        
        /// <remarks/>
        CANCELADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class localDateTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class genero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int generoIdField;
        
        private bool generoIdFieldSpecified;
        
        private string nombreEnField;
        
        private string nombreEsField;
        
        private pelicula[] peliculasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int generoId {
            get {
                return this.generoIdField;
            }
            set {
                this.generoIdField = value;
                this.RaisePropertyChanged("generoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoIdSpecified {
            get {
                return this.generoIdFieldSpecified;
            }
            set {
                this.generoIdFieldSpecified = value;
                this.RaisePropertyChanged("generoIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreEn {
            get {
                return this.nombreEnField;
            }
            set {
                this.nombreEnField = value;
                this.RaisePropertyChanged("nombreEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreEs {
            get {
                return this.nombreEsField;
            }
            set {
                this.nombreEsField = value;
                this.RaisePropertyChanged("nombreEs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("peliculas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public pelicula[] peliculas {
            get {
                return this.peliculasField;
            }
            set {
                this.peliculasField = value;
                this.RaisePropertyChanged("peliculas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class asiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private ushort filaField;
        
        private int idField;
        
        private int numeroField;
        
        private sala salaField;
        
        private tipoAsiento tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort fila {
            get {
                return this.filaField;
            }
            set {
                this.filaField = value;
                this.RaisePropertyChanged("fila");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public sala sala {
            get {
                return this.salaField;
            }
            set {
                this.salaField = value;
                this.RaisePropertyChanged("sala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoAsiento tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class sala : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private asiento[] asientosField;
        
        private int capacidadField;
        
        private int idField;
        
        private string nombreField;
        
        private tipoSala tipoSalaField;
        
        private bool tipoSalaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("asientos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public asiento[] asientos {
            get {
                return this.asientosField;
            }
            set {
                this.asientosField = value;
                this.RaisePropertyChanged("asientos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                this.capacidadField = value;
                this.RaisePropertyChanged("capacidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoSala tipoSala {
            get {
                return this.tipoSalaField;
            }
            set {
                this.tipoSalaField = value;
                this.RaisePropertyChanged("tipoSala");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSalaSpecified {
            get {
                return this.tipoSalaFieldSpecified;
            }
            set {
                this.tipoSalaFieldSpecified = value;
                this.RaisePropertyChanged("tipoSalaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public enum tipoSala {
        
        /// <remarks/>
        ESTANDAR,
        
        /// <remarks/>
        TRES_D,
        
        /// <remarks/>
        PREMIUM,
        
        /// <remarks/>
        CUATRO_DX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public enum tipoAsiento {
        
        /// <remarks/>
        NORMAL,
        
        /// <remarks/>
        VIP,
        
        /// <remarks/>
        DISCAPACITADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private bool estaActivoField;
        
        private localDate fechaRegistroField;
        
        private int idField;
        
        private string idiomaPreferidoField;
        
        private string nombreField;
        
        private string passwordField;
        
        private string telefonoField;
        
        private tipoUsuario tipoUsuarioField;
        
        private bool tipoUsuarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estaActivo {
            get {
                return this.estaActivoField;
            }
            set {
                this.estaActivoField = value;
                this.RaisePropertyChanged("estaActivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDate fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idiomaPreferido {
            get {
                return this.idiomaPreferidoField;
            }
            set {
                this.idiomaPreferidoField = value;
                this.RaisePropertyChanged("idiomaPreferido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoUsuario tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioSpecified {
            get {
                return this.tipoUsuarioFieldSpecified;
            }
            set {
                this.tipoUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/")]
    public enum metodoPago {
        
        /// <remarks/>
        QR,
        
        /// <remarks/>
        TARJETA,
        
        /// <remarks/>
        EFECTIVO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPelicula", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class registrarPeliculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.PeliculaWebService.pelicula arg0;
        
        public registrarPeliculaRequest() {
        }
        
        public registrarPeliculaRequest(AutoServicioCineWeb.PeliculaWebService.pelicula arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPeliculaResponse", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class registrarPeliculaResponse {
        
        public registrarPeliculaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPelicula", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class actualizarPeliculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.PeliculaWebService.pelicula arg0;
        
        public actualizarPeliculaRequest() {
        }
        
        public actualizarPeliculaRequest(AutoServicioCineWeb.PeliculaWebService.pelicula arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPeliculaResponse", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class actualizarPeliculaResponse {
        
        public actualizarPeliculaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPeliculas", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class listarPeliculasRequest {
        
        public listarPeliculasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPeliculasResponse", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class listarPeliculasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.PeliculaWebService.pelicula[] @return;
        
        public listarPeliculasResponse() {
        }
        
        public listarPeliculasResponse(AutoServicioCineWeb.PeliculaWebService.pelicula[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPeliculaPorId", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class buscarPeliculaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarPeliculaPorIdRequest() {
        }
        
        public buscarPeliculaPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPeliculaPorIdResponse", WrapperNamespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class buscarPeliculaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://autoserviciopucpwsbl.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.PeliculaWebService.pelicula @return;
        
        public buscarPeliculaPorIdResponse() {
        }
        
        public buscarPeliculaPorIdResponse(AutoServicioCineWeb.PeliculaWebService.pelicula @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeliculaWSChannel : AutoServicioCineWeb.PeliculaWebService.PeliculaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeliculaWSClient : System.ServiceModel.ClientBase<AutoServicioCineWeb.PeliculaWebService.PeliculaWS>, AutoServicioCineWeb.PeliculaWebService.PeliculaWS {
        
        public PeliculaWSClient() {
        }
        
        public PeliculaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeliculaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeliculaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaResponse AutoServicioCineWeb.PeliculaWebService.PeliculaWS.eliminarPelicula(AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest request) {
            return base.Channel.eliminarPelicula(request);
        }
        
        public void eliminarPelicula(int arg0) {
            AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest inValue = new AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaResponse retVal = ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).eliminarPelicula(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaResponse> AutoServicioCineWeb.PeliculaWebService.PeliculaWS.eliminarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest request) {
            return base.Channel.eliminarPeliculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaResponse> eliminarPeliculaAsync(int arg0) {
            AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest inValue = new AutoServicioCineWeb.PeliculaWebService.eliminarPeliculaRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).eliminarPeliculaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.PeliculaWebService.registrarPeliculaResponse AutoServicioCineWeb.PeliculaWebService.PeliculaWS.registrarPelicula(AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest request) {
            return base.Channel.registrarPelicula(request);
        }
        
        public void registrarPelicula(AutoServicioCineWeb.PeliculaWebService.pelicula arg0) {
            AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest inValue = new AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.PeliculaWebService.registrarPeliculaResponse retVal = ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).registrarPelicula(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.registrarPeliculaResponse> AutoServicioCineWeb.PeliculaWebService.PeliculaWS.registrarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest request) {
            return base.Channel.registrarPeliculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.registrarPeliculaResponse> registrarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.pelicula arg0) {
            AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest inValue = new AutoServicioCineWeb.PeliculaWebService.registrarPeliculaRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).registrarPeliculaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaResponse AutoServicioCineWeb.PeliculaWebService.PeliculaWS.actualizarPelicula(AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest request) {
            return base.Channel.actualizarPelicula(request);
        }
        
        public void actualizarPelicula(AutoServicioCineWeb.PeliculaWebService.pelicula arg0) {
            AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest inValue = new AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaResponse retVal = ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).actualizarPelicula(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaResponse> AutoServicioCineWeb.PeliculaWebService.PeliculaWS.actualizarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest request) {
            return base.Channel.actualizarPeliculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaResponse> actualizarPeliculaAsync(AutoServicioCineWeb.PeliculaWebService.pelicula arg0) {
            AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest inValue = new AutoServicioCineWeb.PeliculaWebService.actualizarPeliculaRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).actualizarPeliculaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.PeliculaWebService.listarPeliculasResponse AutoServicioCineWeb.PeliculaWebService.PeliculaWS.listarPeliculas(AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest request) {
            return base.Channel.listarPeliculas(request);
        }
        
        public AutoServicioCineWeb.PeliculaWebService.pelicula[] listarPeliculas() {
            AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest inValue = new AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest();
            AutoServicioCineWeb.PeliculaWebService.listarPeliculasResponse retVal = ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).listarPeliculas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.listarPeliculasResponse> AutoServicioCineWeb.PeliculaWebService.PeliculaWS.listarPeliculasAsync(AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest request) {
            return base.Channel.listarPeliculasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.listarPeliculasResponse> listarPeliculasAsync() {
            AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest inValue = new AutoServicioCineWeb.PeliculaWebService.listarPeliculasRequest();
            return ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).listarPeliculasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdResponse AutoServicioCineWeb.PeliculaWebService.PeliculaWS.buscarPeliculaPorId(AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest request) {
            return base.Channel.buscarPeliculaPorId(request);
        }
        
        public AutoServicioCineWeb.PeliculaWebService.pelicula buscarPeliculaPorId(int arg0) {
            AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest inValue = new AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdResponse retVal = ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).buscarPeliculaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdResponse> AutoServicioCineWeb.PeliculaWebService.PeliculaWS.buscarPeliculaPorIdAsync(AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest request) {
            return base.Channel.buscarPeliculaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdResponse> buscarPeliculaPorIdAsync(int arg0) {
            AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest inValue = new AutoServicioCineWeb.PeliculaWebService.buscarPeliculaPorIdRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.PeliculaWebService.PeliculaWS)(this)).buscarPeliculaPorIdAsync(inValue);
        }
    }
}
