//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServicioCineWeb.ComidaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", ConfigurationName="ComidaWS.ComidaWS")]
    public interface ComidaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/buscarComidaPorIdReq" +
            "uest", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/buscarComidaPorIdRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutoServicioCineWeb.ComidaWS.buscarComidaPorIdResponse buscarComidaPorId(AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/buscarComidaPorIdReq" +
            "uest", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/buscarComidaPorIdRes" +
            "ponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.buscarComidaPorIdResponse> buscarComidaPorIdAsync(AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/listarComidasRequest" +
            "", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/listarComidasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutoServicioCineWeb.ComidaWS.listarComidasResponse listarComidas(AutoServicioCineWeb.ComidaWS.listarComidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/listarComidasRequest" +
            "", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/listarComidasRespons" +
            "e")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.listarComidasResponse> listarComidasAsync(AutoServicioCineWeb.ComidaWS.listarComidasRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/actualizaComidaReque" +
            "st", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/actualizaComidaRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.ComidaWS.actualizaComidaResponse actualizaComida(AutoServicioCineWeb.ComidaWS.actualizaComidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/actualizaComidaReque" +
            "st", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/actualizaComidaRespo" +
            "nse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.actualizaComidaResponse> actualizaComidaAsync(AutoServicioCineWeb.ComidaWS.actualizaComidaRequest request);
        
        // CODEGEN: Parameter 'comida' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/registrarComidaReque" +
            "st", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/registrarComidaRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.ComidaWS.registrarComidaResponse registrarComida(AutoServicioCineWeb.ComidaWS.registrarComidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/registrarComidaReque" +
            "st", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/registrarComidaRespo" +
            "nse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.registrarComidaResponse> registrarComidaAsync(AutoServicioCineWeb.ComidaWS.registrarComidaRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/eliminarComidaReques" +
            "t", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/eliminarComidaRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.ComidaWS.eliminarComidaResponse eliminarComida(AutoServicioCineWeb.ComidaWS.eliminarComidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/eliminarComidaReques" +
            "t", ReplyAction="http://WS.autoservicio.autoservicio.cinepucp.com.pe/ComidaWS/eliminarComidaRespon" +
            "se")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.eliminarComidaResponse> eliminarComidaAsync(AutoServicioCineWeb.ComidaWS.eliminarComidaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private bool estaActivoField;
        
        private int idField;
        
        private string nombreField;
        
        private double precioField;
        
        private tipoProducto tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estaActivo {
            get {
                return this.estaActivoField;
            }
            set {
                this.estaActivoField = value;
                this.RaisePropertyChanged("estaActivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoProducto tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/")]
    public enum tipoProducto {
        
        /// <remarks/>
        BEBIDA,
        
        /// <remarks/>
        SNACK,
        
        /// <remarks/>
        COMBO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarComidaPorId", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class buscarComidaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarComidaPorIdRequest() {
        }
        
        public buscarComidaPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarComidaPorIdResponse", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class buscarComidaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.ComidaWS.producto @return;
        
        public buscarComidaPorIdResponse() {
        }
        
        public buscarComidaPorIdResponse(AutoServicioCineWeb.ComidaWS.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarComidas", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class listarComidasRequest {
        
        public listarComidasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarComidasResponse", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class listarComidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.ComidaWS.producto[] @return;
        
        public listarComidasResponse() {
        }
        
        public listarComidasResponse(AutoServicioCineWeb.ComidaWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizaComida", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class actualizaComidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.ComidaWS.producto arg0;
        
        public actualizaComidaRequest() {
        }
        
        public actualizaComidaRequest(AutoServicioCineWeb.ComidaWS.producto arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizaComidaResponse", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class actualizaComidaResponse {
        
        public actualizaComidaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarComida", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class registrarComidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.ComidaWS.producto comida;
        
        public registrarComidaRequest() {
        }
        
        public registrarComidaRequest(AutoServicioCineWeb.ComidaWS.producto comida) {
            this.comida = comida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarComidaResponse", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class registrarComidaResponse {
        
        public registrarComidaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarComida", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class eliminarComidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarComidaRequest() {
        }
        
        public eliminarComidaRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarComidaResponse", WrapperNamespace="http://WS.autoservicio.autoservicio.cinepucp.com.pe/", IsWrapped=true)]
    public partial class eliminarComidaResponse {
        
        public eliminarComidaResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComidaWSChannel : AutoServicioCineWeb.ComidaWS.ComidaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComidaWSClient : System.ServiceModel.ClientBase<AutoServicioCineWeb.ComidaWS.ComidaWS>, AutoServicioCineWeb.ComidaWS.ComidaWS {
        
        public ComidaWSClient() {
        }
        
        public ComidaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComidaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComidaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComidaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.ComidaWS.buscarComidaPorIdResponse AutoServicioCineWeb.ComidaWS.ComidaWS.buscarComidaPorId(AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest request) {
            return base.Channel.buscarComidaPorId(request);
        }
        
        public AutoServicioCineWeb.ComidaWS.producto buscarComidaPorId(int arg0) {
            AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest inValue = new AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.ComidaWS.buscarComidaPorIdResponse retVal = ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).buscarComidaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.buscarComidaPorIdResponse> AutoServicioCineWeb.ComidaWS.ComidaWS.buscarComidaPorIdAsync(AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest request) {
            return base.Channel.buscarComidaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.buscarComidaPorIdResponse> buscarComidaPorIdAsync(int arg0) {
            AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest inValue = new AutoServicioCineWeb.ComidaWS.buscarComidaPorIdRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).buscarComidaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.ComidaWS.listarComidasResponse AutoServicioCineWeb.ComidaWS.ComidaWS.listarComidas(AutoServicioCineWeb.ComidaWS.listarComidasRequest request) {
            return base.Channel.listarComidas(request);
        }
        
        public AutoServicioCineWeb.ComidaWS.producto[] listarComidas() {
            AutoServicioCineWeb.ComidaWS.listarComidasRequest inValue = new AutoServicioCineWeb.ComidaWS.listarComidasRequest();
            AutoServicioCineWeb.ComidaWS.listarComidasResponse retVal = ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).listarComidas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.listarComidasResponse> AutoServicioCineWeb.ComidaWS.ComidaWS.listarComidasAsync(AutoServicioCineWeb.ComidaWS.listarComidasRequest request) {
            return base.Channel.listarComidasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.listarComidasResponse> listarComidasAsync() {
            AutoServicioCineWeb.ComidaWS.listarComidasRequest inValue = new AutoServicioCineWeb.ComidaWS.listarComidasRequest();
            return ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).listarComidasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.ComidaWS.actualizaComidaResponse AutoServicioCineWeb.ComidaWS.ComidaWS.actualizaComida(AutoServicioCineWeb.ComidaWS.actualizaComidaRequest request) {
            return base.Channel.actualizaComida(request);
        }
        
        public void actualizaComida(AutoServicioCineWeb.ComidaWS.producto arg0) {
            AutoServicioCineWeb.ComidaWS.actualizaComidaRequest inValue = new AutoServicioCineWeb.ComidaWS.actualizaComidaRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.ComidaWS.actualizaComidaResponse retVal = ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).actualizaComida(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.actualizaComidaResponse> AutoServicioCineWeb.ComidaWS.ComidaWS.actualizaComidaAsync(AutoServicioCineWeb.ComidaWS.actualizaComidaRequest request) {
            return base.Channel.actualizaComidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.actualizaComidaResponse> actualizaComidaAsync(AutoServicioCineWeb.ComidaWS.producto arg0) {
            AutoServicioCineWeb.ComidaWS.actualizaComidaRequest inValue = new AutoServicioCineWeb.ComidaWS.actualizaComidaRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).actualizaComidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.ComidaWS.registrarComidaResponse AutoServicioCineWeb.ComidaWS.ComidaWS.registrarComida(AutoServicioCineWeb.ComidaWS.registrarComidaRequest request) {
            return base.Channel.registrarComida(request);
        }
        
        public void registrarComida(AutoServicioCineWeb.ComidaWS.producto comida) {
            AutoServicioCineWeb.ComidaWS.registrarComidaRequest inValue = new AutoServicioCineWeb.ComidaWS.registrarComidaRequest();
            inValue.comida = comida;
            AutoServicioCineWeb.ComidaWS.registrarComidaResponse retVal = ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).registrarComida(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.registrarComidaResponse> AutoServicioCineWeb.ComidaWS.ComidaWS.registrarComidaAsync(AutoServicioCineWeb.ComidaWS.registrarComidaRequest request) {
            return base.Channel.registrarComidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.registrarComidaResponse> registrarComidaAsync(AutoServicioCineWeb.ComidaWS.producto comida) {
            AutoServicioCineWeb.ComidaWS.registrarComidaRequest inValue = new AutoServicioCineWeb.ComidaWS.registrarComidaRequest();
            inValue.comida = comida;
            return ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).registrarComidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.ComidaWS.eliminarComidaResponse AutoServicioCineWeb.ComidaWS.ComidaWS.eliminarComida(AutoServicioCineWeb.ComidaWS.eliminarComidaRequest request) {
            return base.Channel.eliminarComida(request);
        }
        
        public void eliminarComida(int arg0) {
            AutoServicioCineWeb.ComidaWS.eliminarComidaRequest inValue = new AutoServicioCineWeb.ComidaWS.eliminarComidaRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.ComidaWS.eliminarComidaResponse retVal = ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).eliminarComida(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.eliminarComidaResponse> AutoServicioCineWeb.ComidaWS.ComidaWS.eliminarComidaAsync(AutoServicioCineWeb.ComidaWS.eliminarComidaRequest request) {
            return base.Channel.eliminarComidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.ComidaWS.eliminarComidaResponse> eliminarComidaAsync(int arg0) {
            AutoServicioCineWeb.ComidaWS.eliminarComidaRequest inValue = new AutoServicioCineWeb.ComidaWS.eliminarComidaRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.ComidaWS.ComidaWS)(this)).eliminarComidaAsync(inValue);
        }
    }
}
