//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServicioCineWeb.CuponWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/", ConfigurationName="CuponWS.CuponWS")]
    public interface CuponWS {
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/eliminarCuponRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/eliminarCuponResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.CuponWS.eliminarCuponResponse eliminarCupon(AutoServicioCineWeb.CuponWS.eliminarCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/eliminarCuponRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/eliminarCuponResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.eliminarCuponResponse> eliminarCuponAsync(AutoServicioCineWeb.CuponWS.eliminarCuponRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/buscarCuponPorIdRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/buscarCuponPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutoServicioCineWeb.CuponWS.buscarCuponPorIdResponse buscarCuponPorId(AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/buscarCuponPorIdRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/buscarCuponPorIdResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.buscarCuponPorIdResponse> buscarCuponPorIdAsync(AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/registrarCuponRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/registrarCuponResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.CuponWS.registrarCuponResponse registrarCupon(AutoServicioCineWeb.CuponWS.registrarCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/registrarCuponRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/registrarCuponResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.registrarCuponResponse> registrarCuponAsync(AutoServicioCineWeb.CuponWS.registrarCuponRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/listarCuponesRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/listarCuponesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutoServicioCineWeb.CuponWS.listarCuponesResponse listarCupones(AutoServicioCineWeb.CuponWS.listarCuponesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/listarCuponesRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/listarCuponesResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.listarCuponesResponse> listarCuponesAsync(AutoServicioCineWeb.CuponWS.listarCuponesRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/actualizarCuponRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/actualizarCuponResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoServicioCineWeb.CuponWS.actualizarCuponResponse actualizarCupon(AutoServicioCineWeb.CuponWS.actualizarCuponRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.AutoCine.pucp.edu.pe/CuponWS/actualizarCuponRequest", ReplyAction="http://services.AutoCine.pucp.edu.pe/CuponWS/actualizarCuponResponse")]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.actualizarCuponResponse> actualizarCuponAsync(AutoServicioCineWeb.CuponWS.actualizarCuponRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCupon", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarCuponRequest() {
        }
        
        public eliminarCuponRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuponResponse", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCuponResponse {
        
        public eliminarCuponResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/")]
    public partial class cupon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private usuario creadoPorField;
        
        private int cuponIdField;
        
        private bool cuponIdFieldSpecified;
        
        private string descripcionEnField;
        
        private string descripcionEsField;
        
        private tipoDescuento descuentoTipoField;
        
        private bool descuentoTipoFieldSpecified;
        
        private double descuentoValorField;
        
        private bool descuentoValorFieldSpecified;
        
        private localDate fechaFinField;
        
        private localDate fechaInicioField;
        
        private localDate fechaModificacionField;
        
        private int maxUsosField;
        
        private bool maxUsosFieldSpecified;
        
        private int usosActualesField;
        
        private bool usosActualesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public usuario creadoPor {
            get {
                return this.creadoPorField;
            }
            set {
                this.creadoPorField = value;
                this.RaisePropertyChanged("creadoPor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cuponId {
            get {
                return this.cuponIdField;
            }
            set {
                this.cuponIdField = value;
                this.RaisePropertyChanged("cuponId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cuponIdSpecified {
            get {
                return this.cuponIdFieldSpecified;
            }
            set {
                this.cuponIdFieldSpecified = value;
                this.RaisePropertyChanged("cuponIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcionEn {
            get {
                return this.descripcionEnField;
            }
            set {
                this.descripcionEnField = value;
                this.RaisePropertyChanged("descripcionEn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descripcionEs {
            get {
                return this.descripcionEsField;
            }
            set {
                this.descripcionEsField = value;
                this.RaisePropertyChanged("descripcionEs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoDescuento descuentoTipo {
            get {
                return this.descuentoTipoField;
            }
            set {
                this.descuentoTipoField = value;
                this.RaisePropertyChanged("descuentoTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoTipoSpecified {
            get {
                return this.descuentoTipoFieldSpecified;
            }
            set {
                this.descuentoTipoFieldSpecified = value;
                this.RaisePropertyChanged("descuentoTipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double descuentoValor {
            get {
                return this.descuentoValorField;
            }
            set {
                this.descuentoValorField = value;
                this.RaisePropertyChanged("descuentoValor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoValorSpecified {
            get {
                return this.descuentoValorFieldSpecified;
            }
            set {
                this.descuentoValorFieldSpecified = value;
                this.RaisePropertyChanged("descuentoValorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public localDate fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public localDate fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public localDate fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int maxUsos {
            get {
                return this.maxUsosField;
            }
            set {
                this.maxUsosField = value;
                this.RaisePropertyChanged("maxUsos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxUsosSpecified {
            get {
                return this.maxUsosFieldSpecified;
            }
            set {
                this.maxUsosFieldSpecified = value;
                this.RaisePropertyChanged("maxUsosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int usosActuales {
            get {
                return this.usosActualesField;
            }
            set {
                this.usosActualesField = value;
                this.RaisePropertyChanged("usosActuales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usosActualesSpecified {
            get {
                return this.usosActualesFieldSpecified;
            }
            set {
                this.usosActualesFieldSpecified = value;
                this.RaisePropertyChanged("usosActualesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private bool estaActivoField;
        
        private localDate fechaRegistroField;
        
        private int idField;
        
        private string idiomaPreferidoField;
        
        private string nombreField;
        
        private string passwordField;
        
        private string telefonoField;
        
        private tipoUsuario tipoUsuarioField;
        
        private bool tipoUsuarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estaActivo {
            get {
                return this.estaActivoField;
            }
            set {
                this.estaActivoField = value;
                this.RaisePropertyChanged("estaActivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localDate fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idiomaPreferido {
            get {
                return this.idiomaPreferidoField;
            }
            set {
                this.idiomaPreferidoField = value;
                this.RaisePropertyChanged("idiomaPreferido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoUsuario tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioSpecified {
            get {
                return this.tipoUsuarioFieldSpecified;
            }
            set {
                this.tipoUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/")]
    public enum tipoUsuario {
        
        /// <remarks/>
        CLIENTE,
        
        /// <remarks/>
        ADMIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/")]
    public enum tipoDescuento {
        
        /// <remarks/>
        PORCENTAJE,
        
        /// <remarks/>
        MONTO_FIJO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCuponPorId", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarCuponPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public buscarCuponPorIdRequest() {
        }
        
        public buscarCuponPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCuponPorIdResponse", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarCuponPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.CuponWS.cupon @return;
        
        public buscarCuponPorIdResponse() {
        }
        
        public buscarCuponPorIdResponse(AutoServicioCineWeb.CuponWS.cupon @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarCupon", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.CuponWS.cupon arg0;
        
        public registrarCuponRequest() {
        }
        
        public registrarCuponRequest(AutoServicioCineWeb.CuponWS.cupon arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarCuponResponse", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class registrarCuponResponse {
        
        public registrarCuponResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCupones", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuponesRequest {
        
        public listarCuponesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuponesResponse", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCuponesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.CuponWS.cupon[] @return;
        
        public listarCuponesResponse() {
        }
        
        public listarCuponesResponse(AutoServicioCineWeb.CuponWS.cupon[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCupon", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCuponRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.AutoCine.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AutoServicioCineWeb.CuponWS.cupon arg0;
        
        public actualizarCuponRequest() {
        }
        
        public actualizarCuponRequest(AutoServicioCineWeb.CuponWS.cupon arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCuponResponse", WrapperNamespace="http://services.AutoCine.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCuponResponse {
        
        public actualizarCuponResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuponWSChannel : AutoServicioCineWeb.CuponWS.CuponWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuponWSClient : System.ServiceModel.ClientBase<AutoServicioCineWeb.CuponWS.CuponWS>, AutoServicioCineWeb.CuponWS.CuponWS {
        
        public CuponWSClient() {
        }
        
        public CuponWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuponWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuponWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuponWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.CuponWS.eliminarCuponResponse AutoServicioCineWeb.CuponWS.CuponWS.eliminarCupon(AutoServicioCineWeb.CuponWS.eliminarCuponRequest request) {
            return base.Channel.eliminarCupon(request);
        }
        
        public void eliminarCupon(int arg0) {
            AutoServicioCineWeb.CuponWS.eliminarCuponRequest inValue = new AutoServicioCineWeb.CuponWS.eliminarCuponRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.CuponWS.eliminarCuponResponse retVal = ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).eliminarCupon(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.eliminarCuponResponse> AutoServicioCineWeb.CuponWS.CuponWS.eliminarCuponAsync(AutoServicioCineWeb.CuponWS.eliminarCuponRequest request) {
            return base.Channel.eliminarCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.eliminarCuponResponse> eliminarCuponAsync(int arg0) {
            AutoServicioCineWeb.CuponWS.eliminarCuponRequest inValue = new AutoServicioCineWeb.CuponWS.eliminarCuponRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).eliminarCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.CuponWS.buscarCuponPorIdResponse AutoServicioCineWeb.CuponWS.CuponWS.buscarCuponPorId(AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest request) {
            return base.Channel.buscarCuponPorId(request);
        }
        
        public AutoServicioCineWeb.CuponWS.cupon buscarCuponPorId(int arg0) {
            AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest inValue = new AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.CuponWS.buscarCuponPorIdResponse retVal = ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).buscarCuponPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.buscarCuponPorIdResponse> AutoServicioCineWeb.CuponWS.CuponWS.buscarCuponPorIdAsync(AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest request) {
            return base.Channel.buscarCuponPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.buscarCuponPorIdResponse> buscarCuponPorIdAsync(int arg0) {
            AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest inValue = new AutoServicioCineWeb.CuponWS.buscarCuponPorIdRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).buscarCuponPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.CuponWS.registrarCuponResponse AutoServicioCineWeb.CuponWS.CuponWS.registrarCupon(AutoServicioCineWeb.CuponWS.registrarCuponRequest request) {
            return base.Channel.registrarCupon(request);
        }
        
        public void registrarCupon(AutoServicioCineWeb.CuponWS.cupon arg0) {
            AutoServicioCineWeb.CuponWS.registrarCuponRequest inValue = new AutoServicioCineWeb.CuponWS.registrarCuponRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.CuponWS.registrarCuponResponse retVal = ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).registrarCupon(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.registrarCuponResponse> AutoServicioCineWeb.CuponWS.CuponWS.registrarCuponAsync(AutoServicioCineWeb.CuponWS.registrarCuponRequest request) {
            return base.Channel.registrarCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.registrarCuponResponse> registrarCuponAsync(AutoServicioCineWeb.CuponWS.cupon arg0) {
            AutoServicioCineWeb.CuponWS.registrarCuponRequest inValue = new AutoServicioCineWeb.CuponWS.registrarCuponRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).registrarCuponAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.CuponWS.listarCuponesResponse AutoServicioCineWeb.CuponWS.CuponWS.listarCupones(AutoServicioCineWeb.CuponWS.listarCuponesRequest request) {
            return base.Channel.listarCupones(request);
        }
        
        public AutoServicioCineWeb.CuponWS.cupon[] listarCupones() {
            AutoServicioCineWeb.CuponWS.listarCuponesRequest inValue = new AutoServicioCineWeb.CuponWS.listarCuponesRequest();
            AutoServicioCineWeb.CuponWS.listarCuponesResponse retVal = ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).listarCupones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.listarCuponesResponse> AutoServicioCineWeb.CuponWS.CuponWS.listarCuponesAsync(AutoServicioCineWeb.CuponWS.listarCuponesRequest request) {
            return base.Channel.listarCuponesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.listarCuponesResponse> listarCuponesAsync() {
            AutoServicioCineWeb.CuponWS.listarCuponesRequest inValue = new AutoServicioCineWeb.CuponWS.listarCuponesRequest();
            return ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).listarCuponesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoServicioCineWeb.CuponWS.actualizarCuponResponse AutoServicioCineWeb.CuponWS.CuponWS.actualizarCupon(AutoServicioCineWeb.CuponWS.actualizarCuponRequest request) {
            return base.Channel.actualizarCupon(request);
        }
        
        public void actualizarCupon(AutoServicioCineWeb.CuponWS.cupon arg0) {
            AutoServicioCineWeb.CuponWS.actualizarCuponRequest inValue = new AutoServicioCineWeb.CuponWS.actualizarCuponRequest();
            inValue.arg0 = arg0;
            AutoServicioCineWeb.CuponWS.actualizarCuponResponse retVal = ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).actualizarCupon(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.actualizarCuponResponse> AutoServicioCineWeb.CuponWS.CuponWS.actualizarCuponAsync(AutoServicioCineWeb.CuponWS.actualizarCuponRequest request) {
            return base.Channel.actualizarCuponAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoServicioCineWeb.CuponWS.actualizarCuponResponse> actualizarCuponAsync(AutoServicioCineWeb.CuponWS.cupon arg0) {
            AutoServicioCineWeb.CuponWS.actualizarCuponRequest inValue = new AutoServicioCineWeb.CuponWS.actualizarCuponRequest();
            inValue.arg0 = arg0;
            return ((AutoServicioCineWeb.CuponWS.CuponWS)(this)).actualizarCuponAsync(inValue);
        }
    }
}
